### ISSUE TITLE
move CanEMS5 members from scratch to permanent bucket?

### ISSUE THREAD

**Issue by hatlenheimdalthea** [leap-stc/CMIP6-pCO2-testbed#3]
Can you move the 18 re-gridded CanESM5 members to the permanent bucket before they get deleted?

**Comment by jbusecke** [comment]
You should be able to do that yourself with the existing permissions. 

You can do something like this:
```python
import gcsfs
fs = gcsfs.GCSFileSystem()
fs.mv('path-on-scratch', 'new-path-on-persistent', recursive=True)
```
